[window]
opacity = 0.9
blur = true

[window.padding]
x = 15
y = 15

[font]
size = 12

[font.normal]
family = "Fira Code"
style = "Normal"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[colors.primary]
foreground = "#aaaaaa"
background = "#000000"

[mouse]
hide_when_typing = true

